- name: Build panos config using Ansible Jinjia2 template

  hosts: localhost
  gather_facts: no

  vars_files:
    - /Users/fabriziomaccioni/src/forward-cicd-ansible/forward.properties

  vars:
    - fw_name: "{{lookup('file', 'firewall_name')}}"

  tasks:
    - template:
        src=templates/panos-rule.j2
        dest=configs/{{ fw_name }}_rule.txt

    - template:
        src=templates/panos-address.j2
        dest=configs/{{ fw_name }}_address.txt
