---

- name: Change Security policy on Palo Alto Networks device
  hosts: 10.10.20.27
  connection: local
  gather_facts: no

  vars:
    # Read firewall_ip from file created by is_change_needed Python script
    firewall_ip: "{{lookup('file', 'firewall_ip')}}"

  # I have no found a way to configure a jump host for panos devices.
  # This playbook is copied and run in the remote server by Jenkins
  vars_files:
    - /root/forward.properties
#    - /var/lib/jenkins/forward.properties

  roles:
    - role: paloaltonetworks.paloaltonetworks

  tasks:
      # Task based on this module:
      # https://github.com/PaloAltoNetworks/ansible-pan/blob/master/library/panos_address_object.py
    - name: Create server object
      panos_address_object:
        ip_address: '{{ firewall_ip }}'
        username: '{{ panos_user }}'
        password: '{{ panos_password }}'
        name: '{{ service_name }} server'
        value: '{{ server_ip }}/32'
        description: '{{ service_name }} server object'
        state: 'present'

      # Task based on this module:
      # https://github.com/PaloAltoNetworks/ansible-pan/blob/master/library/panos_security_rule.py
    - name: Add Security Rules
      panos_security_rule:
        ip_address: '{{ firewall_ip }}'
        username: '{{ panos_user }}'
        password: '{{ panos_password }}'
        rule_name: 'Allow {{ service_name }} service'
        description: 'permit access to {{ service_name }} service'
        destination_ip: '{{ service_name }} server'
        category: ['any']
        application: ['any']
        action: 'allow'
        commit: yes
        location: 'top'
