---

- name: Change Security policy on Palo Alto Networks device
  hosts: 10.10.20.27
  connection: local
  gather_facts: no

  # I have no found a way to configure a jump host for panos devices.
  # This playbook is copied and run in the remote server by Jenkins
  vars_files:
    - /root/forward.properties
#    - /var/lib/jenkins/forward.properties

  roles:
    - role: paloaltonetworks.paloaltonetworks

# https://github.com/PaloAltoNetworks/ansible-pan/blob/master/library/panos_security_rule.py
  tasks:
    - name: Change Security Rules
      panos_security_rule:
        ip_address: '{{ panos_ip }}'
        username: '{{ panos_user }}'
        password: '{{ panos_password }}'
        rule_name: 'Allow Arrodugo service'
        description: 'permit access to Arrodugo service'
        destination_ip: 'Arrodugo server'
        category: ['any']
        application: ['any']
        action: 'allow'
        commit: yes
        location: 'top'
