- name: Pre-change validation. Check if the path is already present

  hosts: localhost
  gather_facts: no

  vars_files:
    - /var/lib/jenkins/forward.properties

  vars:
    # Define the default expected security and forwarding outcome status
    expected_security_outcome_status: DENIED      # options: PERMITTED, DENIED
    expected_forwarding_outcome_status: DELIVERED # options: DELIVERED, DELIVERED_TO_INCORRECT_LOCATION, BLACKHOLE, DROPPED, INADMISSIBLE, UNREACHABLE, LOOP

  tasks:
    - name: get best path using the Forward Paths REST API
      uri:
        url: "{{url}}/api/snapshots/{{snapshot_id}}/paths?srcIp={{src_ip}}&dstIp={{server_ip}}&dstPort={{dst_port}}"
        method: GET
        force_basic_auth: yes
        user: "{{ username }}"
        password: "{{ password }}"
        body_format: json
        return_content: yes
      register: paths_output

    - name: Print Paths info
      debug:
        msg:
          - "API URL: {{ paths_output.url }}"
          - "API Status: {{ paths_output.status }}"
          - "Paths Security Outcome: {{ paths_output.json.info.paths[0].securityOutcome }}"
          - "Paths forwarding Outcome: {{ paths_output.json.info.paths[0].forwardingOutcome }}"

    - name: Save json output to file
      copy:
        content: "{{ paths_output.json }}"
        dest: "paths.json"
