- name: Post-change validation. Get all the Checks and save results.

  hosts: localhost
  gather_facts: no

  vars_files:
    - /var/lib/jenkins/forward.properties

  tasks:
    - name: GET all the Forward Checks using the Forward Checks REST API
      uri:
        url: "{{url}}/api/snapshots/{{lookup('file', './tmp/new_snapshot_id')}}/checks"
        method: GET
        force_basic_auth: yes
        user: "{{ username }}"
        password: "{{ password }}"
        body_format: json
        return_content: yes
      register: checks_output

    - name: Print API status info
      debug:
        msg:
          - "API URL: {{ checks_output.url }}"
          - "API Status: {{ checks_output.status }}"

    - name: Save json output to file
      copy:
        content: "{{ checks_output.json }}"
        dest: "./tmp/checks.json"
