- name: Add an Intent Check to verify that the new service is OK

  hosts: localhost
  gather_facts: no

  vars_files:
    - /var/lib/jenkins/forward.properties

  vars:
    expected_check_status: PASS  # Default status

  tasks:
    - name: Ensure a check matching new service intent is present
      forward_check:
        url:  https://app.forwardnetworks.com
        state: Present
        name: "Check added by Jenkins CI/CD Pipeline"
        type: "typical_5_tuple"
        data:
          source: "{{srcIp}}"
          ipv4_dst: "{{dstIp}}"
#          ip_proto: tcp
#          tp_src: http
          tp_dst: "{{dstPort}}"
      register: check_output
#      failed_when: check_output.result.status != expected_check_status

    - name: Print Check info
      debug:
        msg:
          - "Dump all output: : {{ check_output }}"
