- name: Add an Intent Check to verify that the new service is OK

  hosts: localhost
  gather_facts: no

  vars_files:
    - /var/lib/jenkins/forward.properties

  # playbooks that include forward modules are not run in the Jenkins WORKSPACE
  # because are installed locally
  vars:
    expected_check_status: PASS  # Default status
    fw_name_path: "{{lookup('env','WORKSPACE')}}/tmp"
    # Read service ip and port from local file
    service_ip:   "{{lookup('file', '{{fw_name_path}}/service_ip')}}"
    service_port: "{{lookup('file', '{{fw_name_path}}/service_port')}}"
    clients:      "{{lookup('file', '{{fw_name_path}}/clients')}}"

  tasks:
    - name: Ensure a check matching new service intent is present
      forward_check:
        url: "{{ url }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: Present
        name: "Check added by Jenkins CI/CD Pipeline"
        type: "typical_5_tuple"
        network_name: "{{network_name}}"
        data:
          source_host: "{{clients}}"
          ipv4_dst: "{{service_ip}}"
          tp_dst: "{{service_port}}"
      register: check_output
#      failed_when: check_output.result.status != expected_check_status

    - name: Print Check info
      debug:
        msg:
          - "Dump all output: : {{ check_output }}"
