- name: Add an Intent Check to verify that the new service is OK

  hosts: localhost
  gather_facts: no

  vars_files:
    - /var/lib/jenkins/forward.properties

  vars:
    expected_check_status: PASS  # Default status

  tasks:
    - name: Ensure a check matching new service intent is present
      forward_check:
        state: Present
        name: "Check added by Jenkins CI/CD Pipeline"
        type: "typical_5_tuple"
        data:
          source: "ESXi-2_vSwitch23"
          ipv4_dst: "10.110.57.34"
          ip_proto: tcp
          tp_src: http
          tp_dst: https
      register: check_output
#      failed_when: check_output.result.status != expected_check_status

    - name: Print Check info
      debug:
        msg:
          - "API Status: {{ check_output.status }}"
          - "API URL: {{ check_output.url }}"
          - "Dump all output: : {{ check_output.status }}"
