- name: Pre-change validation. Check if the path is already present

  hosts: localhost

  vars_files:
    - /var/lib/jenkins/forward.properties

  vars:
    expected_check_status: PASS  # Default status for the test (after change)

  tasks:
    - name: get best path using the Forward Paths REST API
      uri:
#        url: https://{{base_url}}/snapshots/{{snapshotId}}/paths?srcIp={{srcIp}}&dstIp={{dstIp}}&intent={{intent}}&ipProto={{ipProto}}&srcPort={{srcPort}}&dstPort={{dstPort}}&includeNetworkFunctions=false&maxResults=1&maxReturnPathResults=0&maxSeconds=30
        url: https://{{base_url}}/snapshots/{{snapshotId}}/paths?srcIp={{srcIp}}&dstIp={{dstIp}}&dstPort={{dstPort}}
        method: GET
        force_basic_auth: yes
        user: "{{ username }}"
        password: "{{ password }}"
        body_format: json
        return_content: yes
      register: paths_output

    - name: Print Paths info
      debug:
        msg:
          - "Status: {{ paths_output.status }}"
          - "URL: {{ paths_output.url }}"
#          - "Security Outcome: {{ paths_output.json.info.paths.securityOutcome }}"

    - name: Save all output to file
      copy:
        content: "{{ paths_output }}"
        dest: "paths.output"

    - name: Save json output to file
      copy:
        content: "{{ paths_output.json }}"
        dest: "paths.json"
