- name: Pre-change validation. Check if the path is already present

  hosts: localhost

  vars_files:
    - forward.properties

  vars:
    expected_check_status: PASS  # Default status for the test (after change)

  tasks:
    - name: get best path using the Forward Paths REST API
      uri:
        url: https://{{base_url}}/snapshots/{{snapshotId_paths}}/paths?srcIp={{srcIp}}&dstIp={{dstIp}}&intent={{intent}}&ipProto={{ipProto}}&srcPort={{srcPort}}&dstPort={{dstPort}}&includeNetworkFunctions=false&maxResults=1&maxReturnPathResults=0&maxSeconds=30
        method: GET
        force_basic_auth: yes
        user: "{{ username }}"
        password: "{{ password }}"
        body_format: json
        return_content: yes
      register: path_output

    - name: Print Paths info
      debug:
        msg:
          - "Status: {{ networks_output.status }}"
          - "URL: {{ networks_output.url }}"
#          - "Security Outcome: {{ networks_output.json.info.paths.securityOutcome }}"

    - name: Save all output to file
      copy:
        content: "{{ path_output }}"
        dest: "path.output"

    - name: Save json output to file
      copy:
        content: "{{ path_output.json }}"
        dest: "path.json"
