---

- name: Rollback Security policy on Palo Alto Networks device
  hosts: eve_panos
  connection: local
  gather_facts: no

  vars_files:
    - /var/lib/jenkins/forward.properties

  roles:
    - role: paloaltonetworks.paloaltonetworks

# https://github.com/PaloAltoNetworks/ansible-pan/blob/master/library/panos_security_rule.py
  tasks:
    - name: Change Security Rules
      panos_security_rule:
        ip_address: '{{ panos_ip }}'
        username: '{{ panos_user }}'
        password: '{{ panos_password }}'
        rule_name: 'permit ACME service'
        description: 'Permit access to ACME server on https'
        destination_ip: '{{ panosDstIp }}'
        category: ['any']
        application: ['any']
        action: 'allow'
        operation: delete
        commit: yes
