---

- name: Rollback Security policy on Palo Alto Networks device
  hosts: 10.10.20.27
  connection: local
  gather_facts: no

  # I have no found a way to configure a jump host for panos devices.
  # This playbook is copied and run in the remote server by Jenkins
  vars_files:
    - /root/forward.properties

  roles:
    - role: paloaltonetworks.paloaltonetworks


  tasks:

      # https://github.com/PaloAltoNetworks/ansible-pan/blob/master/library/panos_address_object.py
    - name: Delete server object
      panos_address_object:
        ip_address: '{{ panos_ip }}'
        username: '{{ panos_user }}'
        password: '{{ panos_password }}'
        name: 'Arrodugo server'
        state: 'absent'

      # https://github.com/PaloAltoNetworks/ansible-pan/blob/master/library/panos_security_rule.py
    - name: Remove Security Rules
      panos_security_rule:
        ip_address: '{{ panos_ip }}'
        username: '{{ panos_user }}'
        password: '{{ panos_password }}'
        rule_name: 'Allow Arrodugo service'
        state: absent
        commit: yes
