- name: Save changes in the Forward Enterprise Sandox

  hosts: localhost
  gather_facts: no

  vars:
    # Read firewall_name from file created by is_change_needed Python script
    firewall_name:  "{{lookup('file', './tmp/firewall_name')}}"
    fw_config_path: "{{lookup('env','WORKSPACE')}}/tmp/{{ firewall_name }}_config.txt"

  vars_files:
    - /var/lib/jenkins/forward.properties

  tasks:

      #### Step 1: fork the given snapshot ####
    - name: Fork current snapshot
      uri:
        url: "{{url}}/api/snapshots/{{snapshot_id}}/fork?snapshotName=cicd-testing"
        method: POST
        force_basic_auth: yes
        user: "{{ username }}"
        password: "{{ password }}"
        body_format: json
        return_content: yes
      register: fork_output

    - name: Print Snapshot Fork info
      debug:
        msg:
          - "API URL: {{ fork_output.url }}"
          - "API Status: {{ fork_output.status }}"
          - "Fork id: {{ fork_output.json.id }}"

    #### Step 2: Save changes into Sanbox by uploading the new device config ####
    - name: Save changes into Sandox
      shell: 'curl  -X "POST" "{{url}}/api/snapshots/{{fork_output.json.id}}/files" -u {{ username }}:{{ password }} -F "file=@{{ fw_config_path }}"  -k'
      register: save_output

    #### Step 3: Commit change to Sandbox  ####
    - name: Commit changes in Sandox
      uri:
        url: "{{url}}/api/snapshots/{{fork_output.json.id}}/commit?changed"
        method: POST
        force_basic_auth: yes
        user: "{{ username }}"
        password: "{{ password }}"
        body_format: json
        return_content: yes
      register: commit_output

    - name: Print Commit Changes info
      debug:
        msg:
          - "API URL: {{ commit_output.url }}"
          - "API Status: {{ commit_output.status }}"
          - "New snapshot id: {{ commit_output.json.id }}"

    # the predict snapshot id is saved to a local file so that can be used
    # to get the checks in the get_snapshot playbook
    - name: Save predict snapshot id to a local file
      copy:
        content: "{{ commit_output.json.id }}"
        dest: "./tmp/new_snapshot_id"
