- name: Take a Partial Collection from devices with changes only

  hosts: localhost
  gather_facts: no

  vars_files:
    - /var/lib/jenkins/forward.properties

  tasks:

      ###### STEP 1: Start a Partial Collection ######
    - name: Start Partial Collection
      uri:
        url: https://{{base_url}}/networks/{{network_id}}/startcollection
        method: POST
        force_basic_auth: yes
        user: "{{ username }}"
        password: "{{ password }}"
        body_format: json
        body:
          devices: ["a70*"]
        return_content: yes
      register: collection_output

    - name: Print Collection info
      debug:
        msg:
          - "API Status: {{ collection_output.status }}"
          - "API URL: {{ collection_output.url }}"
          - "Collection output: {{ collection_output }}"

      ###### STEP 2: wait until the collection is over ######
      #
      # Make sure the collection is over by monitoring the busy status of the
      # network's collector and see when the status changes from COLLECTING to IDLE
    - name: Make sure the collection is over
      uri:
        url: https://{{base_url}}/networks/{{network_id}}/collector/status
        method: GET
        force_basic_auth: yes
        user: "{{ username }}"
        password: "{{ password }}"
        body_format: json
        return_content: yes
      register: collector_status_output
      until: collector_status_output.json.busyStatus != "COLLECTING"
      retries: 5
      delay: 15

    - name: Print Collector Status info
      debug:
        msg:
          - "API Status: {{ collector_status_output.status }}"
          - "API URL: {{ collector_status_output.url }}"
          - "Collector busyStatus: {{ collector_status_output.json.busyStatus }}"

      ###### STEP 3: wait until the snapshot processing is over ######
      #
      # Make sure the snapshot processing is over by comparing the
      # latestProcessed id with the partial collection snapshot id (it's the
      # first in the snapshots list)
    - name: Get the list of all snapshots
      uri:
        url: https://{{base_url}}/networks/{{network_id}}/snapshots
        force_basic_auth: yes
        user: "{{ username }}"
        password: "{{ password }}"
        body_format: json
        return_content: yes
      register: snapshots_output

    - name: Print Snapshots Status info
      debug:
        msg:
          - "API Status: {{ snapshots_output.status }}"
          - "API URL: {{ snapshots_output.url }}"
          - "Snapshots: {{ snapshots_output.json.snapshots }}"
          - "Partial collection id: {{ snapshots_output.json.snapshots[0].id }}"

    - name: Make sure the collection is over by checking the latestProcessed id
      uri:
        url: https://{{base_url}}/networks/{{network_id}}/latestProcessed
        force_basic_auth: yes
        user: "{{ username }}"
        password: "{{ password }}"
        body_format: json
        return_content: yes
      register: latest_processed_output
#      until: latest_processed_output.json.id == snapshots_output.json.snapshots[0].id
#      retries: 5
#      delay: 15

    - name: Print latestProcessed Status info
      debug:
        msg:
          - "API Status: {{ latest_processed_output.status }}"
          - "API URL: {{ latest_processed_output.url }}"
#          - "latestProcessed id: {{ latest_processed_output.json.id }}"
          - "latestProcessed output: {{ latest_processed_output }}"
