- name: Take a Partial Collection from devices with changes only

  hosts: localhost
  gather_facts: no

  vars_files:
    - /var/lib/jenkins/forward.properties

  vars:
    # Define the default expected security and forwarding outcome status
    expected_security_outcome_status: DENIED      # options: PERMITTED, DENIED
    expected_forwarding_outcome_status: DELIVERED # options: DELIVERED, DELIVERED_TO_INCORRECT_LOCATION, BLACKHOLE, DROPPED, INADMISSIBLE, UNREACHABLE, LOOP

  tasks:
    - name: Start Partial Collection
      uri:
        url: https://{{base_url}}/networks/{{network_id}}/startcollection
        method: POST
        force_basic_auth: yes
        user: "{{ username }}"
        password: "{{ password }}"
        body_format: json
        body:
          devices: ["a70*"]
        return_content: yes
      register: collection_output
#      failed_when: collection_output.json.info.paths[0].forwardingOutcome != expected_forwarding_outcome_status

    - name: Print Paths info
      debug:
        msg:
          - "API Status: {{ collection_output.status }}"
          - "API URL: {{ collection_output.url }}"
