- name: Ensure HTTP/HTTPS traffic between ESXi virtual switches matches our expectation
  hosts: localhost
  vars:
    expected_check_status: PASS  # Default status for the test (after change)

  tasks:
    - name: Ensure a check matching our intent is present, and has the expected value
      forward_check:
        state: Present
        name: "Check added by Ansible"
        type: "typical_5_tuple"
        data:
          source: "ESXi-2_vSwitch23"
          ipv4_dst: "10.110.57.34"
          ip_proto: tcp
          tp_src: http
          tp_dst: https
      register: check_output
      failed_when: check_output.result.status != expected_check_status
