- name: Verify changes in the Forward Enterprise Sandox

  hosts: localhost
  gather_facts: no

  vars_files:
    - /var/lib/jenkins/forward.properties

  vars:
    # Define the default expected security and forwarding outcome status
    expected_security_outcome_status: DENIED      # options: PERMITTED, DENIED
    expected_forwarding_outcome_status: DELIVERED # options: DELIVERED, DELIVERED_TO_INCORRECT_LOCATION, BLACKHOLE, DROPPED, INADMISSIBLE, UNREACHABLE, LOOP

  tasks:
    - name: Fork current snapshot
      uri:
        url: https://{{base_url}}/snapshots/243646/fork?snapshotName=snapshot-fork
        method: POST
        force_basic_auth: yes
        user: "{{ username }}"
        password: "{{ password }}"
        body_format: json
        return_content: yes
      register: fork_output
#      failed_when: collection_output.json.info.paths[0].forwardingOutcome != expected_forwarding_outcome_status

    - name: Print Snapshot Fork info
      debug:
        msg:
          - "API Status: {{ fork_output.status }}"
          - "API URL: {{ fork_output.url }}"
          - "Fork ID: {{ fork_output.id }}"
          - "Fork output: {{ fork_output }}"


    - name: Save changes in Sandox
      uri:
        url: https://{{base_url}}/snapshots/{{fork_output.id}}/files
        method: POST
        force_basic_auth: yes
        user: "{{ username }}"
        password: "{{ password }}"
        body_format: form-data
        body:
          - name: "file"
          - filename: "/var/lib/jenkins/a7048_config.txt"
        return_content: yes
      register: save_output
#      failed_when: collection_output.json.info.paths[0].forwardingOutcome != expected_forwarding_outcome_status

    - name: Print Save Changes info
      debug:
        msg:
          - "API Status: {{ save_output.status }}"
          - "API URL: {{ save_output.url }}"
          - "Save output: {{ save_output }}"


    - name: Commit changes in Sandox
      uri:
        url: https://{{base_url}}/snapshots/{{fork_output.id}}/commit?changed
        method: POST
        force_basic_auth: yes
        user: "{{ username }}"
        password: "{{ password }}"
        body_format: json
        return_content: yes
      register: commit_output
#      failed_when: collection_output.json.info.paths[0].forwardingOutcome != expected_forwarding_outcome_status

    - name: Print Commit Changes info
      debug:
        msg:
          - "API Status: {{ commit_output.status }}"
          - "API URL: {{ commit_output.url }}"
          - "Commit output: {{ commit_output }}"
